const data = {
    products:[
       {
            _id:'1',
            name: 'Golf Shirt',
            category:'Casual Wear',
            image: '/images/men3.png',
            price: 249.99,
            brand: 'Oakridge',
            rating: 4.5,
            numReviews: 10,
            description:'High Quality Casual Wear',
        },
        {
            _id:'2',
            name: 'Slim Dress',
            category: 'Ladies',
            image: '/images/women4.png',
            price: 499.00,
            brand: 'Sassy',
            rating: 7.5,
            numReviews: 10,
            description:'High Quality Casual Wear',
        },
        {
            _id:'3',
            name: 'Toddle Bunny Costume',
            category:'Kiddies',
            image: '/images/bunny.jpg',
            price: 149.95,
            brand: 'Jabaroo',
            rating: 8,
            numReviews: 10,
            description:'High Quality Casual Wear',
        },
        {
            _id:'4',
            name: 'Toddler Hoodie Jacket',
            category:'Kiddies',
            image: '/images/boys1.png',
            price: 79.95,
            brand: 'Jabaroo',
            rating: 6,
            numReviews: 10,
            description:'High Quality Casual Wear',
        },
        {
            _id: '5',
            name:'Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 489.99,
            brand: 'Docker',
            rating: 4.5,
            numReviews: 10,
            description:'High Quality Casual Wear',
        },
    ],
};
export default data;